id: 16
name: ASSEMBLY
cards: 6
points: 10
display: 3 + 3 (two types)
flavor: Brick for stone, bitumen for mortar, rising as one.
context: Defying the Noahic mandate to disperse and fill the earth, humanity congregated
  at Shinar to consolidate power and manufacture a name for themselves (Genesis 11:4).
  This gathering illustrates the theological peril of unity founded upon anthropocentric
  pride rather than submission to God's sovereign rule.
render_attempts: 1
final_score: 100
