id: 21
name: HYMNAL
cards: 6
points: 10
display: ADJ x2 + VERB x2 + NOUN x2
flavor: A harmony of pride shattered into a chaos of tongues.
context: The builders of Babel utilized their "one language" to compose a liturgy
  of human autonomy, seeking to make a name for themselves rather than glorify the
  Creator (Genesis 11:4). This phase represents the redemption of the collective voice,
  reorienting speech from a tool of prideful rebellion into a harmonized instrument
  of divine praise.
render_attempts: 2
final_score: 95
