number: '002'
word: BUILD
gloss: To construct, establish, or edify; to raise a structure or strengthen a community.
card_type: VERB
rarity: COMMON
series: 2026-Q1
set: Babel
art_prompt: Rough-hewn stone blocks stacking upward into a golden light, a plumb line
  hanging straight down in the foreground, ancient architectural style, warm lighting,
  digital painting
stats:
  lore: 2
  context: 4
  complexity: 2
ability: Look at the top 2 cards of the Tower; put one into your hand and the other
  on the bottom.
ot_verse:
  ref: Psalm 127:1
  snippet: Unless the Lord builds the house, the builders labor in vain.
nt_verse:
  ref: Matthew 16:18
  snippet: On this rock I will build my church, and the gates of Hades will not overcome
    it.
greek:
  text: οἰκοδομέω
  translit: oikodomeō
hebrew:
  text: בָּנָה
  translit: banah
ot_refs: Gen 11:4 • 1 Kings 6:1 • Neh 4:6 • Prov 24:3
nt_refs: Matt 7:24 • 1 Cor 3:10 • Eph 2:20 • 1 Pet 2:5
trivia:
- The Hebrew word for 'son' (ben) shares the same root as 'build' (banah), implying
  sons build the family line.
- In Genesis 2:22, God 'built' Eve from Adam's rib, using the architectural verb rather
  than 'formed' or 'created'.
- Jesus is often called a carpenter, but the Greek 'tekton' can more broadly mean
  a builder or stonemason.
wild_id: null
wild_counts_as: null
quartet_id: null
letter: null
notes: null
sources: []
search_queries: []
