number: '007'
word: SANCTIFY
gloss: To set apart for sacred use; to cleanse or make holy.
card_type: VERB
rarity: RARE
series: 2026-Q1
set: Example
art_prompt: A golden censer swinging in a dark void, releasing billowing clouds of
  white incense smoke that catch a shaft of intense, vertical divine light; the light
  illuminates a single pristine ceramic vessel while leaving the surrounding area
  in shadow.
stats:
  lore: 5
  context: 3
  complexity: 4
ability: Look at the top 3 cards of the Tower. Add 2 to your hand and exile the third.
style_series_dir: series\2026-Q1
review_score: 95
review_attempts: 2
last_description:
  card_number_format: '#007'
  stat_pip_shape: circle
  stat_pip_fill_color: gold
  has_brackets: false
  bracket_locations: []
  style_matches_reference: true
  style_mismatch_reason: ''
review_status: yellow
review_notes: Increase LORE stat pips from 3 to 5; Increase CONTEXT stat pips from
  2 to 3; Increase COMPLEXITY stat pips from 2 to 4
user_action_required: true
user_warning: Card scored 95/100. Please review and revise manually.
