#!/usr/bin/env python3
"""Wrap an artifact page into a standalone document for GitHub Pages.

The artifact host supplies a doctype, a viewport meta and a small reset around
the page body; a page served from Pages has to bring its own. This script takes
the artifact source - which begins with its <title> and <style> and then runs
straight into markup - splits it at the end of its stylesheet, and rebuilds it
as a complete HTML document with the same reset, a favicon, and the social
cards a link needs when it is posted somewhere.

    python scripts/site/wrap_page.py --in page.html --out docs/site/index.html
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

SITE = "https://bobbyhiddn.github.io/Hypertext/"

# The artifact runtime's reset, reproduced so the page renders identically off-host.
RESET = """<style>
:root{color-scheme:light dark}
html,body{margin:0}
body{font:14px system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;background:#faf9f7}
img{max-width:100%}
[hidden]{display:none!important}
</style>"""

FAVICON = (
    '<link rel="icon" href="data:image/svg+xml,'
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E"
    "%3Ctext y='.9em' font-size='90'%3E%F0%9F%97%BC%3C/text%3E%3C/svg%3E\">"
)


def split_head(src: str) -> tuple[str, str]:
    """Everything up to the last </style> that precedes the first block element."""
    first_block = re.search(r"<(?:div|header|main|section|body)\b", src)
    cut = src.rfind("</style>", 0, first_block.start() if first_block else len(src))
    if cut == -1:
        return "", src
    cut += len("</style>")
    return src[:cut], src[cut:]


def build(src: str, *, title: str, description: str, og_image: str) -> str:
    head, body = split_head(src)
    meta = "\n".join([
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f'<meta name="description" content="{description}">',
        f'<meta property="og:title" content="{title}">',
        f'<meta property="og:description" content="{description}">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:url" content="{SITE}">',
        f'<meta property="og:image" content="{SITE}{og_image}">',
        '<meta name="twitter:card" content="summary_large_image">',
        FAVICON,
    ])
    return (
        "<!doctype html>\n<html lang=\"en\">\n<head>\n"
        f"{meta}\n{RESET}\n{head.strip()}\n</head>\n<body>\n{body.strip()}\n</body>\n</html>\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="src", required=True, type=Path)
    ap.add_argument("--out", dest="out", required=True, type=Path)
    ap.add_argument("--title", default="Hypertext Towerfall")
    ap.add_argument(
        "--description",
        default=(
            "A biblical word-study trading card game: 90 Word Cards and 30 Lots, "
            "generated by a gated pipeline and printed for playtesting."
        ),
    )
    ap.add_argument("--og-image", default="og.jpg")
    args = ap.parse_args()

    page = build(
        args.src.read_text(encoding="utf-8"),
        title=args.title,
        description=args.description,
        og_image=args.og_image,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(page, encoding="utf-8")
    print(f"wrote {args.out} ({len(page) // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
