id: 3
name: SCROLL
cards: 5
points: 8
display: NAME + VERB + ADJ + NOUN + TITLE
flavor: The ink preserves what the confused tongue has lost.
context: Symbolizing the preservation of divine revelation, the scroll stands as a
  testament to God's immutable truth amidst the linguistic fracture of the nations
  at Shinar. It marks the unfolding of redemptive history, ensuring the knowledge
  of Yahweh transcends the confusion of tongues recorded in Genesis 11.
render_attempts: 1
final_score: 95
