id: 17
name: TRINITY
cards: 6
points: 10
display: 2 + 2 + 2 (three types)
flavor: Three voices speak as one, descending to scatter the proud.
context: The divine plural in Genesis 11:7—"Come, let us go down"—foreshadows the
  collaborative agency of the Triune Godhead acting in judgment. This revelation contrasts
  the perfect, uncreated unity of the Father, Son, and Spirit with the rebellious,
  manufactured unity of mankind.
render_attempts: 1
final_score: 100
