id: 14
name: LAMENT
cards: 5
points: 8
display: ADJ + ADJ + ADJ + ADJ + NOUN
flavor: Beneath the unfinished tower, we sat down and wept.
context: Lament functions as the theological corrective to the hubris of Shinar, acknowledging
  that the fracture of human unity is a tragedy requiring divine intervention. By
  mourning the confusion of tongues (Genesis 11:9), the faithful turn from the chaos
  of self-exaltation to a posture of humble dependence.
render_attempts: 1
final_score: 100
