number: '011'
word: MOSES
gloss: The great prophet, lawgiver, and deliverer who led Israel out of Egypt.
card_type: NAME
rarity: RARE
art_prompt: A weathered ancient figure in rough robes standing on a jagged mountain
  peak, holding two stone tablets, illuminated by a divine golden light from above,
  with a vast desert encampment visible far below, cinematic lighting, realistic style
stats:
  lore: 5
  context: 5
  complexity: 4
ability: Return 1 card from Sheol to your hand, then draw 1.
ot_verse:
  ref: Exodus 33:11
  snippet: The Lord would speak to Moses face to face, as one speaks to a friend.
nt_verse:
  ref: John 1:17
  snippet: For the law was given through Moses; grace and truth came through Jesus
    Christ.
greek:
  text: Μωϋσῆς
  translit: Mōusēs
hebrew:
  text: מֹשֶׁה
  translit: Mosheh
ot_refs: Exodus 2 • Exodus 14 • Exodus 20 • Numbers 12 • Deuteronomy 34
nt_refs: Matthew 17 • Acts 7 • Hebrews 11 • Jude 9 • Revelation 15
trivia:
- His name sounds like the Hebrew verb 'mashah', meaning 'to draw out'.
- 'Lived 120 years: 40 in Egypt, 40 in Midian, and 40 in the wilderness.'
- The only person in the Bible described as speaking with God 'face to face'.
- Traditionally credited with writing the Pentateuch (the first five books of the
  Bible).
- Appeared alongside Elijah during the Transfiguration of Jesus.
wild_id: null
wild_counts_as: null
quartet_id: null
letter: null
notes: null
sources: []
search_queries: []
review_score: 100
review_attempts: 2
last_description:
  card_number_format: '#011'
  stat_pip_shape: circle
  stat_pip_fill_color: navy
  has_brackets: false
  bracket_locations: []
review_status: green
