number: '003'
word: COVENANT
gloss: A solemn, binding agreement or compact between two parties, often sealed by
  an oath or blood sacrifice.
card_type: NOUN
rarity: GLORIOUS
art_prompt: A glowing path of fire passing between two halves of a divided stone altar
  under a vast, starry night sky, cinematic lighting, photorealistic style
stats:
  lore: 5
  context: 5
  complexity: 4
ability: Declare a suit. All other players give you a card of that suit. If they cannot,
  they reveal their hand.
ot_verse:
  ref: Jeremiah 31:31
  snippet: Behold, the days are coming... when I will make a new covenant with the
    house of Israel.
nt_verse:
  ref: Luke 22:20
  snippet: This cup that is poured out for you is the new covenant in my blood.
greek:
  text: διαθήκη
  translit: diathēkē
hebrew:
  text: בְּרִית
  translit: berit
ot_refs: Gen 9:13 • Gen 15:18 • Ex 24:8 • 2 Sam 23:5 • Hos 6:7
nt_refs: Matt 26:28 • Rom 11:27 • 2 Cor 3:6 • Gal 4:24 • Heb 9:15
trivia:
- The Hebrew phrase 'karat berit' literally means 'to cut a covenant,' referring to
  the ritual of cutting animals in two.
- 'There are five major covenants in the Old Testament: Noahic, Abrahamic, Mosaic,
  Davidic, and the New Covenant prophesied by Jeremiah.'
- The Greek word 'diatheke' was chosen by Septuagint translators over 'syntheke' to
  emphasize God's initiative rather than a mutual contract.
- Covenants are typically accompanied by a sign, such as the rainbow, circumcision,
  or the Sabbath.
wild_id: null
wild_counts_as: null
quartet_id: null
letter: null
notes: null
sources: []
search_queries: []
review_score: 100
review_attempts: 2
review_status: green
