id: 19
name: CHORUS
cards: 6
points: 10
display: VERB x3 + ADJ x3
flavor: A symphony of pride, echoing against the gates of heaven.
context: Reflecting the monolingual unity of Shinar, this phase captures the collective
  voice of humanity united in the prideful declaration, "Come, let us make a name
  for ourselves" (Genesis 11:4). It illustrates how a singular language facilitated
  a consensus of rebellion prior to the divine judgment of dispersion.
render_attempts: 2
final_score: 95
