id: 30
name: APOCALYPSE
cards: 7
points: 12
display: 7 same type
flavor: They reached for heaven, and heaven answered with fire.
context: Derived from the Greek *apokalypsis* meaning "unveiling," this phase signifies
  the eschatological disclosure of God's judgment against the archetypal "Mystery
  Babylon" (Revelation 17:5). It marks the definitive collapse of human hubris, replacing
  the confusion of earthly empires with the revealed sovereignty of the Creator.
render_attempts: 2
final_score: 95
