id: 8
name: ORACLE
cards: 5
points: 8
display: VERB + VERB + ADJ + NAME + NOUN
flavor: One language binds them; a divine word breaks them.
context: Often denoting a "burden" (Hebrew *massa*), an oracle represents a weighty
  prophetic utterance that confronts human hubris with divine judgment. As seen in
  pronouncements against Babylon (Isaiah 13:1), this phase signifies the sovereign
  intrusion of God’s voice to dismantle the confusion of earthly schemes.
render_attempts: 1
final_score: 95
