id: 15
name: CONGREGATION
cards: 6
points: 10
display: 6 any mix
flavor: United by one tongue, they gathered to touch the heavens.
context: The gathering at Shinar illustrates an anthropocentric unity where humanity
  sought to establish its own glory in defiance of the divine command to fill the
  earth (Genesis 11:4). Unlike this rebellious assembly, the true covenant congregation
  gathers not to build a name for itself, but to submit to the sovereignty of Yahweh.
render_attempts: 1
final_score: 100
