created: '2024-12-30'
description: Premium navy/gold trading card template with antique parchment aesthetic
generation:
  model: gemini-3-pro-image-preview
  prompt_file: prompt.txt
  style_refs: []
layout:
  art_panel:
    frame_style: gold inner frame with navy outline
    height_fraction: 0.44
  footer:
    series: bottom-left
  header:
    rarity_badge: top-right
    subtitle: below title
    title: center
    type_circle: top-left corner (navy circle with gold border)
  stats_row:
    pip_style: navy circles (hollow outlines)
    stats:
    - LORE
    - CONTEXT
    - COMPLEXITY
  text_panels:
  - ability
  - ot_verse
  - nt_verse
  - greek_hebrew_strip
  - trivia
name: Card Template v1
specs:
  aspect_ratio: '2:3'
  orientation: vertical
  resolution:
    height: 1536
    width: 1024
style:
  frame:
    border: thick navy with gold trim
    corners: rounded with subtle filigree
  palette:
    background: warm parchment
    ink: near-black
    primary: navy
    secondary: gold
  typography:
    body: clean serif
    labels: uppercase small caps
    title: classic serif display
updated: '2026-01-01 17:26:51'
version: '4'
