id: 12
name: FOUNDATION
cards: 5
points: 8
display: NAME + NAME + NAME + NOUN + VERB
flavor: One language binds the mortar; one purpose lays the stone.
context: The laying of Babel’s foundation (Genesis 11:3-4) epitomizes the anthropocentric
  shift from divine reliance to collective human autonomy. Theologically, this phase
  illustrates the futility of establishing a legacy upon the shifting sands of pride
  rather than the eternal cornerstone of God’s will.
render_attempts: 1
final_score: 95
