id: 27
name: CREATION
cards: 7
points: 12
display: 3 + 2 + 2 (three types)
flavor: With brick for stone, they raised a monument to pride.
context: God’s act of creation *ex nihilo* establishes the sovereign order of the
  cosmos and the mandate for humanity to fill the earth for His glory (Genesis 1:28).
  This foundational epoch sets the standard of divine authority, contrasting the Creator’s
  infinite power with the finite rebellion later manifested at Shinar.
render_attempts: 1
final_score: 100
