id: 25
name: PROPHECY
cards: 6
points: 10
display: ADJ x2 + NAME x2 + NOUN + VERB
flavor: What is built in pride shall be scattered in confusion.
context: Prophecy serves as the divine utterance that pierces human confusion, asserting
  God's sovereign will over the hubris of nations attempting to build apart from Him.
  By dismantling the autonomy of the builders at Shinar, the prophetic word establishes
  the necessity of reliance on God's revelation rather than human innovation (Genesis
  11:7-9).
render_attempts: 1
final_score: 95
