id: 29
name: EXODUS
cards: 7
points: 12
display: VERB x3 + NAME x2 + NOUN x2
flavor: Divided by tongue, they fled to the four winds.
context: The Exodus serves as the archetype of biblical salvation, distinguishing
  the formation of God's covenant people from the imperial ambitions of Babel through
  divine deliverance rather than human achievement. By leading Israel out of Egypt,
  Yahweh establishes His sovereignty over earthly powers and fulfills the promise
  to redeem a people for His own possession (Exodus 6:6-7).
render_attempts: 1
final_score: 95
