id: 11
name: ALTAR
cards: 5
points: 8
display: NOUN + NOUN + NOUN + NOUN + VERB
flavor: Lay your offering of bricks before the face of heaven.
context: Standing in theological opposition to the self-exaltation of Babel, the altar
  represents the authorized locus of divine-human encounter established through humility
  and substitutionary sacrifice. It signifies that access to the heavens is not achieved
  by human engineering, but granted through the covenantal offering.
render_attempts: 1
final_score: 95
