id: 2
name: PENTATEUCH
cards: 5
points: 8
display: 5 different types
flavor: Five sacred scrolls to bind the scattered tongues.
context: Comprising the first five books of the Hebrew canon, the Pentateuch establishes
  the covenantal framework and primeval history, including the judgment of nations
  at Babel (Genesis 11). This foundational era defines the tension between human hubris
  and divine Law, setting the stage for the redemptive election of Abraham.
render_attempts: 1
final_score: 95
