number: '004'
word: GRACE
gloss: Unmerited favor; a gift freely given.
card_type: NOUN
rarity: MYTHIC
art_prompt: Ethereal golden light pouring down from dark storm clouds onto a parched
  desert landscape, causing vibrant wildflowers to bloom instantly where the light
  touches.
stats:
  lore: 5
  context: 5
  complexity: 3
ability: Search the shared deck for any card, reveal it, and add it to your hand.
  Shuffle.
ot_verse:
  ref: Genesis 6:8
  snippet: But Noah found grace in the eyes of the LORD.
nt_verse:
  ref: Ephesians 2:8
  snippet: For by grace you have been saved through faith...
greek:
  text: χάρις
  translit: Charis
hebrew:
  text: חֵן
  translit: Chen
ot_refs: Gen 6:8 • Ex 33:17 • Ps 84:11 • Prov 3:34
nt_refs: Rom 3:24 • Rom 5:20 • Eph 2:8 • Tit 2:11
trivia:
- The Greek word *charis* is the root of English words like 'charity' and 'charisma'.
- In the Old Testament, *chen* comes from a root meaning 'to bend or stoop' in kindness.
- 'Grace is often distinguished from mercy: mercy is withholding punishment, while
  grace is bestowing blessing.'
- The Apostle Paul uses this term over 100 times to describe God's unearned favor.
wild_id: null
wild_counts_as: null
quartet_id: null
letter: null
notes: null
sources: []
search_queries: []
