number: '002'
word: GOSPEL
gloss: Good news; a joyful announcement of victory or salvation
card_type: NOUN
rarity: RARE
art_prompt: A radiant golden sunrise breaking over a dark, rugged mountain range,
  illuminating a lone silhouette of a runner on the peak with a raised staff, symbolizing
  the arrival of hope
stats:
  lore: 4
  context: 5
  complexity: 3
ability: Reveal the top card of the shared deck. If its Context is 4 or higher, add
  it to your hand; otherwise, return it to the bottom.
ot_verse:
  ref: Isaiah 52:7
  snippet: How beautiful upon the mountains are the feet of him that bringeth good
    tidings, that publisheth peace.
nt_verse:
  ref: Romans 1:16
  snippet: 'For I am not ashamed of the gospel of Christ: for it is the power of God
    unto salvation to every one that believeth.'
greek:
  text: εὐαγγέλιον
  translit: Euangelion
hebrew:
  text: בְּשׂוֹרָה
  translit: Besorah
ot_refs: Isa 52:7 • Isa 61:1 • Nah 1:15 • 2 Sam 18:26 • Ps 40:9
nt_refs: Rom 1:16 • Mark 1:1 • 1 Cor 15:1-4 • Matt 24:14 • Rev 14:6
trivia:
- The Old English word 'godspel' literally means 'good story' or 'good tidings,' translating
  the Latin 'evangelium'.
- In secular Greek, the term originally referred to the reward given to a messenger
  for bringing good news, before coming to mean the message itself.
- The Roman Empire used this word to announce the birthday of the Emperor or a military
  victory, making the Christian usage a subversive political claim that Jesus was
  the true King.
wild_id: null
wild_counts_as: null
quartet_id: null
letter: null
notes: null
sources:
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGznu2WIsTK-F8fFKhFUahmSoQJ-dCZBqC9GUeZTJsRA0fqHviPQHgp_zjp17F0rUHcO7ARy75d7QuLQTZUX3HAgreDAW5ffdJ_sBkGn77Api00MnsdzHdJgmUHa1zvYuyvWZX0AbUdRHJD4uGMk5OddhD8eqeXphr9LLvQjnumBM3uNOQ=
  title: cgg.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGxZLSKIrsUpc7rVFAjXlfNzbFjIdNPRfeRZiYtRNu_Q8T3A-pM9w0lWj18b6lB0oEsuO2tz2e8Fi4LGp6DeXebWWw_xLfBTxms_Ry8LctPP1jxgxva6rp6yzTwhfm6GjOppDYzT1it1Wk8
  title: trulyrandomverse.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHggNhGKM-TqBovpWH1sv3iweqw5MFsYjNNMvzhiqFoUfvl0d0_kQBs3JaSs3uO_lB4nOnCiNBhegXeE9yJGle6VvYHx4u8w5ovyMiPaBKvpKcEVg4sNUqhT3ODKZpeYeE_WXK8w7tXf8KIpz8v-H_3a-nr38IabUB30SqWJqTB
  title: compassion.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE3sQB1nUwGml2BGjetk_mDCR6Jpg7BBlZzG9NxOCYTjNfTa5uBQnBFxyVQFrRc3Y9elU6QV57msyXOCQ2aVhl4Z3aUYwh8vd_y25SGHR7MQwzQZ_4ra8f6FMcMtTDxi6N0NqHToCUYHfoXm5Kee8_3uleXV_kbaYvT518=
  title: cara-ray.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFNFNqOmPBQW41CckvNSqjYCNYkhHcCsc_SXCbDIckjzWJRrd9q-MjGlQqWk72TmiGS7S-Hei7tAnycGYffvBygnZdrUUlxpy7ePgjaUOPqyRqxddSCthFiBBC7lk-7VxD72UR1JTWzazSL0l98fWWKhmaW3G-_t2K2RK1S4LKeUf3qC0USzzuF
  title: adornthegospel.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHrdO6kGtEG8u-xy9iT7hcWtwVFnezqaHJb1az4f1EDK51YVyNCRtLPWuFbbsJzXYnWmMtXfR2HOSp9ty901ZTsjZeNMaAYxEcQd_W5iC7pxCm2PGoPjQS9KaGA47DMPtbHORORB-j6rf6RFW1K6_qEUH6bj10O0LAxQzhuD28gwgjuvo6bjj1EsOlsuvjiCAYiT8icgV7Rylg=
  title: nextstepbiblestudy.net
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH5cZPrINlVavJVAydODQBHV8Fx0Zz2uhCFkFBZ_mA1k0clxQ7Klux5z73491pbkzjk-n-6Pf4z_9-odREqQG75oxTvt1j64T-r9cdKSAni4h1Gy51QOqeFFalrhU8P7Q==
  title: biblehub.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHtag2CsgziLe2JSFD0Oj1_uTAvSpAd6q6KUYtnmBg_-hqSdSHewyl-KSARGsALlfyYyTaGub_RTkrK5s7BPvw63YEIlz3TqwS7ek2sRaXgtHy0qNicGJJE_MVjqY2QI4yShf5MrfcW_Ar40Q-WB_OKGQ==
  title: billmounce.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF9DE8usLtumcpBNwudwOwz9Z5hwJza_10uVNSMWzsT3Z5wWMPfNvtO_asgffpnjBrM6xmfev6HbvR5uxGqTlKeBj0AxNx3u0_iPmYZUJT6q4o8I4sX1QAvAdS2AKql
  title: biblehub.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGTvZl9YtrUgSR-xwSIBdNsdBf-F8C9yv8mg65FmHGGDXykp-BRDuFGlU9S_D1r1uoYLerT5zoh9riyV9Cx19kGGYRqae5WcuDW2arCYC-RMng8SkwqFFBGP43BnKv_ssZA7uosg43F0M4Ru2OUHJDI
  title: britannica.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHTAYUb8ECUFuZd2iVmuEGJCLanFPhXau1lk9uu3CqS0g_etvil1dkXn22L41CI38JWEbKE95oxLOIAO8p56_5tiifaqdSftnlbKhxr0s7DaLVex4mE_DEkAO2g6R_FDLOzpx8=
  title: wikipedia.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE-_IK8Q4gdXsfcKOL7eNh2aH-NNI_BBI67Pr6ajFH0fqCVFU9fSSa6Utj7HfAHAxcLAGrJmT4_uQ8VUr_xFFLu0lXJW1FYqe2Yotp8VwVPYBDJobFpinkrQQVdHjCtlWhESAnJ8wg=
  title: youtube.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHywvWcVctoqtDI4k5dLPYJsqkZdRK79g2xMY_5Rg4qM8ORRof2obYHRC1B7N_qZ4lR_300DmMfjmV6cj11g5m1Ru5Lv3GYACEJ5xyW4qNaKyG9ZuaiWZkCJki6GU0u5rTaAgWAC4AmD-fgzhlrQSy42OoeEN4=
  title: bartehrman.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFSbJdYFqsiYyT0bQYAr0ZYw9-CVCe6l0zkCT0BuwErbMZQ0akJPDGMg6rN6dbY47KmkMx1Muo2DeG9ErxWOfhHgUNm7Z_FUpqIhuiZ8PLShavOnRJbRomoPCS3SZ5OkCqcGMvGBrfz_y7TTjJ0LtrlUj2Xm1zTR3bYhWEfJw==
  title: engediresourcecenter.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGvVgYEuB8ZwPcAu4dNiSElct8ABeLvxYMSbR-8Jq7agsxD1XDHQzG4vo0opBT2vHRdSqaA-VGToNJWoftopdphXRRShTtcnH_7hnwSUMssCZHjZXWgHkSh2Zz_TXtdlfjnGi6LNsX8rMAF7hl-460vdCMZ76iOZiCdtQVFZRdJAip1
  title: funtrivia.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFNaw5043s1dYItcCHo68uW0uLsBtiBEcR3Fr2B5YmDyk6Ks_fn2vxkNQbDpg3rS07BB4biLkTzwRCym4CagWD-7voowaTgICndxZDVqdlNhXTt_eFuEVj-vDouPZ77s2oKH6lAL_dbseSnjIM=
  title: verseoftheday.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHrsUb33ziD2KD5DUsNSWhk_cwS9NYBOIsz0H8-XMkyVtyZcc0nzpEcVGE1ljIJe0K0PPvn_OCuJVRQjquGuteeIfVe3ga7q09ms-StbFRlOYbUxJR4vBnzaL4Z1XSeuDFhCuFVVQ6EYfhoFAvwJ6QawIYSHpayQHZZgOCoVZalZxVtnmBo7iOGWSFW6uZB1zMpFF1H--QkSrAJU4-lfSI=
  title: cru.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEuIdCBluWyxLDCT-k6pIjSaYwt4bzphvV-o6NYJFxUE1L92b8FMp_bbBNV2TmMZgGbNT1WwUPDoFTg2z8sZDK1T_6m8lvfFYemYU-vndRgjKhRX26LxkHaAusyjQ9VDQ==
  title: wikipedia.org
search_queries:
- ''
- greek word for gospel in new testament
- trivia about the word gospel
- hebrew word for good news in old testament
- etymology of word gospel greek hebrew
- short bible verses about gospel or good news
