number: '002'
word: GOSPEL
gloss: Good news; a joyful announcement of victory or salvation.
card_type: NOUN
rarity: RARE
art_prompt: A golden sunrise breaking over a dark, rugged mountain range, illuminating
  a valley below with warm, radiant light; a lone runner in the distance silhouetted
  against the light, carrying a banner, dynamic and hopeful atmosphere, oil painting
  style
stats:
  lore: 5
  context: 5
  complexity: 3
ability: When played, reveal the top card of your deck. If its Lore stat is higher
  than this card's Context stat, add it to your hand; otherwise, place it at the bottom
  of your deck.
ot_verse:
  ref: Isaiah 52:7
  snippet: How beautiful upon the mountains are the feet of him that bringeth good
    tidings, that publisheth peace.
nt_verse:
  ref: Romans 1:16
  snippet: 'For I am not ashamed of the gospel of Christ: for it is the power of God
    unto salvation to every one that believeth.'
greek:
  text: εὐαγγέλιον
  translit: euangelion
hebrew:
  text: בָּשַׂר
  translit: basar
ot_refs: Isa 40:9 • Isa 61:1 • Nah 1:15 • 2 Sam 18:31 • Ps 96:2
nt_refs: Mark 1:1 • 1 Cor 15:1-4 • Gal 1:6-9 • Eph 1:13 • Rev 14:6
trivia:
- The English word 'Gospel' derives from the Old English 'godspell', meaning 'good
  story' or 'good news'.
- In the Roman world, 'euangelion' was a political term used for announcements of
  an emperor's birth or military victory.
- The Hebrew root 'basar' originally referred to a messenger bringing fresh news from
  the battlefield, whether good or bad.
- Mark 1:1 is widely considered the first usage of the term to describe a written
  narrative of Jesus' life.
- Paul uses the term 'gospel' more frequently than any other New Testament writer,
  emphasizing it as a proclaimed message.
wild_id: null
wild_counts_as: null
quartet_id: null
letter: null
notes: null
sources:
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFVmblU7N-YgSc3BlmPTWvNMXAUlqoCbmb3HFs8iPt7OrXdNsJMp0hI7kBMi_XBtEYLCUBTgyHP22RCuVdYZhDdPLPKJZTdXvkDpus1B39EJLOSIVXQJHfnoo0T53nn
  title: biblehub.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGR-iCcUG0u0i9cUykOvFmL1UfKhpKJK3cp177wIqEygvTejgLcjvFtlplTinb5_e_7cSINm25FesOUMT-HEx3jLWnN8suOBrqbRuzJW_lEHwDEWuBbXy3WKWoLWnEjN4cTAV61zz1S1TE0Yw2uLwUDb2X9W-A0hftPQVpPQjR7PW8sK5u9sLoeXLA=
  title: bibletools.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQG07qX0AMJLRHEOmgoED3fDMIF3Np7SFekYqEjCrBzYdVu-bHwv_O04jklB-vsQR2Q3ZlYBvzfBSCpVrDZYu7mngXx4D9FBHA9OPyrafv7D6_3d98Xf6xewK2XhTdVqPjIFbjWRas4tY3uwk-a8jlY8YbiN9hFGgoHIPYzZoQmKRjd4FyA=
  title: thoughtcatalog.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF_SYxKCOXlGooi9aZ539SnscSOnp2VAxzra0nAHoiafYoDzN5pVh3wMLprm-wI7ROdl4jhq9NbdExUTIbS-lum5eMCeow1aOIEiK3tWJqxZaphlsEiN18VUidc4-fQkogyWzLzglgx2hq_2A9NGwwn9yo0Q5OwkXwZVqyWjoxk
  title: crossway.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGofGC0DSWm0EFYQlwM5diG3uQPhz87VMHMDm3M2WJE2hcD3wgkh-eCAcZjUrWFaVo1mf404_XdCGu4uMEzU9xbkNnVrZjjM4DXy_BlMglp1fzu04Gu9ndXly2AEJ_kgA==
  title: biblehub.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEi6VXjtfe0GegEzeUXfosjTufKvJRBDZmsm2OAzYf83ga69bopkxbDxZql1EWnXYPiUlY4TNmdq9sKHxIilZJ0rVUYqrFN45bzlBpgELPzK3N4X_xeDGap4rsDydjNK08-80V5e74f0LtMozSn4Pi3Q0qM1ukScNAs0eVPcyXFZH-Um-gQ1uwGxgAjUpAoJDIKFKd1FjBDBJlJCntTTfXEb0e0fbiv2J2P84QIld_IY6oyZcKxTnBLlydu5bCrLQC63ZhbMo4a4NRZt8v33PgcTm9hk51m0k_GBgQHs3reAptsth0ZzbZNSa4d6OxLTqF9P3rQpepKyqLApy7Cevu16BxarIOWCQi-tDwdbdukmCSn32iM2z--hI-1wRmXPpx0s230pryFkY88
  title: tyndale.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEXLWEU5aVQdE-X9ntIiGnH_e6Tqp9q3GF4cqSMtUVXSwieZVr1upNLOwQR56gcn-5IKVvE-KV8R4YoPHWoDeIL-450NHwOcOUvmZUu8mhcfH3rfj5I_-r0W2z4PPfkwHuUnT0=
  title: wikipedia.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE8gm62l0MUdz_cEP3YC3T9pwiYE6uTk3bhBA73vUZ9p7qpkTqMcnCe3ArBHPRFckVjDUU_qBRqR8i0V8zs0KtBEFb4rY2p_tlKk2enUsSaMAmGYd_kMZ0irmlaVh9x_rztammVVvg8IgUqAsq9ZpUzTzOFR55M
  title: dbryen.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH_wDDaE8TBZjsXM4gIclnYQESt6fhAwVPIFHwaQwiFmByl3g4BMMXylgvtbhpEqsh2C6kC6U_5t9VcsBN5GKd_F-W-LCr2FGMaf_0huL2nykRGcxo7nsz3CkgMVEV8WfSIhVLnASslJJjQ5JggQQSo2uZz0vgD59SbZ-pghUZdqqSotQ==
  title: hebrewwordlessons.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFiOSnNMhpFt9NeP4VCLtHapQa5oz2BMg_ADJVdo9IGoQ5_NCBwhVEA7_3zVTk5ywKoIrCEb1uJ1rVEF22rIYgblMU48biRWzcSHuTajvAXNZrxwEa1YPEVpCjH77Ee15I0ZPBeYX1gv1tyGcUvHcS3bbmk1kVr4EXe
  title: aleteia.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEEkSifQHlVBmfkoVIOf4J7UMyQinlIcWj3_zF15xt_Qt8dtAFAoi_VZls3ZyOug_KjkLKqQUVdet6TPg2mzaqBsqQLyZ2tRAj3InCUDBw7JGpYn6Toc3CklxtIKRQl3MNLzwUHy775jgJ3k4hYTriNYr4NgJ6yg393i573
  title: medium.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGNgbf2OpOUyFz9JAtti85NwDdA3AN4XlqYgOD0d-qkDAWXkowKiImrSDWqz4cdfojiC6Vq3kJ-f1Msg0QxcZxC9_9_CEVcteRsfLRZgRDXcCam-y7b-jE5cckRvTS3M8eyUmxShxi13aopbkiImhEjdyhMLTP3444EY1n0HSWcfMquN19dc89qt1Sofb_1pVkD1u0=
  title: studylight.org
search_queries:
- ''
- euangelion greek definition and usage
- basar hebrew definition and usage
- etymology of gospel euangelion basar
- key bible verses for gospel euangelion basar
- gospel word study trivia
