id: 6
name: PSALM
cards: 5
points: 8
display: ADJ + ADJ + ADJ + VERB + NOUN
flavor: From the ruin of language, a new song ascends.
context: Serving as the liturgical response to divine revelation, the Psalms redeem
  human language from the confusion of Babel by reorienting speech toward the glory
  of YHWH. This phase signifies the shift from the hubris of self-exaltation to the
  humble confidence of the "songs of Zion" (Psalm 137:3).
render_attempts: 1
final_score: 95
