id: 9
name: COVENANT
cards: 5
points: 8
display: NAME + VERB + NOUN + NOUN + ADJ
flavor: A covenant of burnt brick, defying the silent stars.
context: Standing in stark contrast to the human autonomy of Babel, the covenant represents
  a sovereign administration of grace wherein God unilaterally binds Himself to a
  people for their redemption. This phase marks the theological pivot from the judgment
  of dispersion to the particular election of a lineage through whom all families
  of the earth will be blessed.
render_attempts: 1
final_score: 95
