id: 23
name: JUBILEE
cards: 6
points: 10
display: VERB x4 + ADJ x2
flavor: A holy blast gathers what the confusion has scattered.
context: Grounded in Leviticus 25, the Jubilee functions as a Sabbath of Sabbaths
  that dismantles systemic debt and servitude, reminding the covenant community that
  the land belongs solely to YHWH. This divine reset opposes the imperial accumulation
  characteristic of Babel, foreshadowing the ultimate eschatological restoration of
  freedom.
render_attempts: 1
final_score: 95
