id: 7
name: PARABLE
cards: 5
points: 8
display: NOUN + NOUN + NOUN + VERB + ADJ
flavor: He who builds to heaven learns the language of dust.
context: Just as the confusion of tongues checked human hubris, the parable serves
  as a hermeneutical veil, concealing the mysteries of the Kingdom from the proud
  while illuminating them for the faithful (Matthew 13:11). This narrative mode necessitates
  spiritual discernment over intellectual might, ensuring that truth is received only
  by those with ears to hear.
render_attempts: 1
final_score: 95
