id: 18
name: TABERNACLE
cards: 6
points: 10
display: NOUN x3 + NAME x3
flavor: Heaven descends to dwell where the tower could not reach.
context: Contrasting the ascending pride of Babel, the Tabernacle signifies God's
  gracious condescension to dwell amidst His people (Exodus 25:8). This sanctuary
  establishes the authorized locus for divine encounter, replacing human confusion
  with covenantal order and foreshadowing the Incarnation.
render_attempts: 1
final_score: 95
