id: 24
name: WISDOM
cards: 6
points: 10
display: ADJ x4 + NOUN x2
flavor: The wise build with humble hearts, not with towers of pride.
context: The narrative of Babel illustrates the futility of human ingenuity divorced
  from divine submission, reminding the believer that true wisdom begins not with
  technical mastery, but with the fear of the Lord (Proverbs 9:10).
render_attempts: 1
final_score: 95
