id: 26
name: SELAH
cards: 6
points: 10
display: 6 same type
flavor: A breath held between the rising stone and falling word.
context: Functioning as a liturgical rubric within the Psalms, *Selah* likely denotes
  a musical interlude or suspension of the voice to facilitate solemn meditation.
  This pause invites the believer to weigh the gravity of divine revelation, contrasting
  the noise of human confusion with the silence of holy reflection.
render_attempts: 1
final_score: 95
