id: 20
name: SANCTUARY
cards: 6
points: 10
display: NOUN x4 + NAME x2
flavor: Find rest within, far from the clamor of confused tongues.
context: In stark contrast to the anthropocentric ascent of Babel, the Sanctuary signifies
  God’s gracious descent to dwell among His people, establishing a holy space for
  covenantal communion (Exodus 25:8).
render_attempts: 1
final_score: 95
