id: 5
name: EPISTLE
cards: 5
points: 8
display: NAME + VERB + VERB + NOUN + NOUN
flavor: Through the ruin of speech, the written word endures.
context: Functioning as the Spirit-inspired connective tissue of the early Church,
  the Epistle counters the fragmentation of Babel by uniting scattered believers under
  apostolic authority. These letters transcend geographic and cultural barriers to
  cultivate a singular mind and doctrine among the body of Christ (1 Cor. 1:10).
render_attempts: 1
final_score: 95
