id: 1
name: REMNANT
cards: 5
points: 8
display: 5 same type
flavor: From the scattering of tongues, the chosen few endure.
context: Amidst the judgment of dispersion at Babel, God sovereignly preserves the
  lineage of Shem, demonstrating that human rebellion cannot thwart redemptive history
  (Genesis 11:10-26). This motif underscores that even in universal apostasy, a faithful
  seed is secured to carry the covenant forward.
render_attempts: 1
final_score: 95
