number: '001'
word: FAITHFUL
gloss: Steadfast in affection or allegiance; firm in adherence to promises; reliable
  and consistent.
card_type: ADJECTIVE
rarity: UNCOMMON
series: 2026-Q1
set: Demo
art_prompt: An ancient, rusted iron anchor wedged firmly into a jagged rock amidst
  crashing ocean waves, illuminated by a single shaft of golden sunlight breaking
  through dark storm clouds.
stats:
  lore: 5
  context: 4
  complexity: 2
ability: Return a card from Sheol to the top of the Tower.
ot_verse:
  ref: Deuteronomy 7:9
  snippet: Know therefore that the LORD thy God... is the faithful God, which keepeth
    covenant and mercy.
nt_verse:
  ref: 2 Timothy 2:13
  snippet: 'If we believe not, yet he abideth faithful: he cannot deny himself.'
greek:
  text: πιστός
  translit: pistos
hebrew:
  text: נֶאֱמָן
  translit: ne'eman
ot_refs: Lam 3:23 • Ps 36:5 • Ps 89:1 • Hos 2:20
nt_refs: 1 Cor 1:9 • 1 Cor 10:13 • 1 John 1:9 • Rev 19:11
trivia:
- The Hebrew adjective 'ne'eman' shares a root with 'amen', meaning 'firm' or 'supported'.
- In Greek, 'pistos' can mean both 'trusting' (active faith) and 'trustworthy' (reliable
  character).
- God's faithfulness is frequently paired with His 'hesed' (loyal love) in the Old
  Testament.
wild_id: null
wild_counts_as: null
quartet_id: null
letter: null
notes: null
sources:
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGdUHglE_QVg-JMCmKeB5y_dA9NDOhvQjYhE94M6XDi8s4oHvOv3lyHOC67mOVw1ycmckK-EzDh387CUf-q75Fn0GXyi5LF5jEac5cMsZ7qqDRCNka4Z_2UGQ6BH2TqlGv3P0VpRmIygwz_Xwyk3sxtzdVHlI-O_hIFDG_FxdUVHkV01EK23YR0E1BZlzqrWpuY-OQnZNk=
  title: medium.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEvaLWFlNX7YZrk-7DFXzu7BR9eSsX5epFCqKTkBFcO88yigif7dbKiID5hOfooLcRtJKxWcRq9Px3Be455Hi_ocmlVrA7LQnbqG5l0w1h7yVvVI-JZ0cly4jh_AyHxczcq_t3WM4RvHp0m-iu7a4lepHOoVK4iAuxz15B8mQnlbLPwlOyTJsmNnagyVVJvfcM-xA4M7zg=
  title: williamstricklandblog.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFbWAArQSOOYwWTGJOOZiUROGEDsk8aXF4_b54HxJgxh36Zr4Ql0ZmMH3VP_lm15gJOHe_-e7BkHGbY83xJkBV9Nh6URCuxszMmBFcuI0_A6HTWB9h03GjDtOklUJDOEX5p3GFFGbHLS8Yii3WfLg==
  title: biblehub.net
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFmGiczfTlOUIOWaeTvvbpJxU3X2WMTUBtrx3vE1g4_GJz9mVEOiV3ORIV-o1H3k6GVx1rJ5u8IFbezbK6h5pwgFZtOnu8RS71rfDAga1i81--CAuX3MSQ7gyyWKrfjjCGl4kIaYq8wp1sqV8L2zfR0XWZJ23K-x4NlEf-Zlrgpt9VbzEyo-fRw9SE=
  title: biblestudytools.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHXkxn6WsxUw8zE-AkLAg_lfOyhma4f_CAjsE7T6VBZb06x7Zeiv56FX4fwiqvGjnLZ1suq1oDhkyu_K-NULpeqDN04Sw2Sew5YBI-wxDMQ6THgqa7af5GA2tz5PMqIndSwgcXpjqxA8k92pR-Eoi1hAjD6c_K7R5JaqBDQyGwXfSJlNj1jpw==
  title: crossway.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEWH8EPQlcm64_PfrARN7coIkrSKYFAHZGi3qfdclJWRcMQS3oqglVn-73gpM2EFr6MiCxISRWvIAPOpR9wtdsYeNonNOpomwG-76iHA47db1ZDDnoVyEE-o7yscAv1S-7NQ-kuWmKC3tvfhRzHzUuJHlE-uVXHRAS1iRgctNnNBESyfQzSpHjPCS9P
  title: bibletools.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEVfKw3W2c7XlPUY3iPB5qWMAfesxEQaPg7ZRkBZn7DsZ22P_YS4-8mAaoxLaZ6nn7TZkxTg-rJq43ziea_wK0dxdIPF2acE3NUJPdAKSuF_GbB4tsAwegfO-D90GYD
  title: biblehub.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEq80x0iYFPGzQIdALmzi-hEzx4ehCbpVL4nNAXwpsnSTgMixReIlDGMI3Q2d04xGyBmnFVXi7tLU-40N5dfsqqO34sb1Fhk9Qrd9x6R7fWHphAjOdxAU7uhR4-4NUDQujBR8e1mEu67LB-kcNPIxJmXUgxo5p2_Ow=
  title: watermark.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGd94JmeNPlri9AtOpZCqzUBWJUocNasWJlXL7JMe4nfOGhs91wvQ4VwQAvu0XDhy0UKfAO5t3GsvMEQ34-0VDn3H0QSRKSaKTSrEgT7LwA_ZyYkQO1zjq-14ZkMq6tMc0d3vPa5UwS_62N7kqOCRFRnEP0ZBwXdtP96tHAc8wYJiiys6GCRKQmuBGqg3rWbaxpAoEhC8D6229aM9t4dNNkxl6yPF6TYZvLJfI2ehXwSsvubrvOsoAL_HHBSIs_j6VZKjfUo94=
  title: medium.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQF2Z0jcbh7oLBqbDpdx9GmLrsMIgPN0gHQaIHriVDts_kSCWi7nXfBUXPwgLeLaCQgjPZRtC_4n4agJh8tQFIRAPH6Pry_YpXWR60t0fneXtbiieulkWu_m4jeKoykrs-9ZI5SOWHkA7MaJiS0bmen37CL3FhEhrVraVXc-gL5xgc15Kaws
  title: wordpress.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE55C5dKDx5zgLK4Cx1eP7ZmevtkF4GinG2oeAHFxQLksQ7YGJ8TfeFe6ARpo9jL9HJpTYAO8IFa34cir8defEmKQ83qkDiJfRUQewKpJKXGBGUZQ9cNTYkVGF5jwI7wYDLkJPq8BLaKYS1bM_B9pwyuIh3IU9piy8Q4eK9e9NWaV2jgwaEgcCIaA==
  title: hebrewwordlessons.com
search_queries:
- ''
- etymology of faithful hebrew amen
- greek word for faithful adjective biblical
- hebrew word for faithful adjective biblical
- faithful bible verses OT NT short
style_series_dir: series/2026-Q1
