number: '003'
word: COVENANT
gloss: A solemn, binding agreement between two parties, often sealed by an oath or
  blood sacrifice.
card_type: NOUN
rarity: GLORIOUS
art_prompt: Two ancient stone tablets glowing with golden light, resting on a rough-hewn
  altar beneath a starry sky, with a faint ethereal cord binding them together.
stats:
  lore: 5
  context: 5
  complexity: 4
ability: Name a suit. Both players search the shared deck for a card of that suit
  and add it to their hand.
ot_verse:
  ref: Jeremiah 31:33
  snippet: I will put my law in their minds and write it on their hearts. I will be
    their God, and they will be my people.
nt_verse:
  ref: Luke 22:20
  snippet: This cup is the new covenant in my blood, which is poured out for you.
greek:
  text: διαθήκη
  translit: Diatheke
hebrew:
  text: בְּרִית
  translit: Berit
ot_refs: Gen 9:9 • Gen 15:18 • Ex 24:8 • Jer 31:31
nt_refs: Matt 26:28 • Heb 8:6 • Heb 9:15 • Gal 3:17
trivia:
- The Hebrew word 'berit' comes from a root meaning 'to cut,' referring to the ancient
  custom of walking between cut animal pieces to seal a pact.
- In Greek, 'diatheke' can also translate to 'last will and testament,' implying an
  inheritance.
- Jeremiah 31 is the only place in the Old Testament where the phrase 'New Covenant'
  is explicitly used.
- Major biblical covenants include those with Noah, Abraham, Moses, and David.
wild_id: null
wild_counts_as: null
quartet_id: null
letter: null
notes: null
sources:
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQE7b4buQrG1p8gnuShSoxQ-jO0gVFUUQto_5Az89XRQKEPmczEYjCeASusD9VXUxl5O8UpfdXfrTi-h4F_Zp6RwEE-N3R9Ky3TtC-UdjP6GBSDCKF7u4xIEqmb_oEgn9s5a5gpagAATgOyZgA17WlXvCMhYA1JAxRfTSWXN7pQNcIrIwoqgXODO02oXkpP1dB88KyYo
  title: biblegateway.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGzx_-pqGRKlWuV4UaEs_gYe69vfCbLys7oIbaBthI2WE4k6HsTsmHNzQvyJCkgKFSl0ndPS1BYtUfeY0vKzdxYchIzdm-uE7eMPegDiT4aRwMc8MFobezoIhcpjlDzhtLcvSY-D3WjbPla2NlC2huF0P80QdxSL0DVgrj-ZK4V358cojV6K96x6axdmyWO3LmRehUCA94YqW8=
  title: vojisrael.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQEaeuIu_qC5OmHVrsxrJZR3FsRTF5yo-18T2lj6SMS479RfCck1k7wLqVs4R2qu-gYplfmdb_9EYrAk4NWi9y9q2wxxrYKksd90gVB1VcReSAcmCbaa-qLtO7BmPTtDlNHNW1rYQYSkU14TJ8Pl
  title: sarata.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFkn4UClzGKK6FNfRHYtMsikZLoIE8Arih8bOpAAnVXcNSJFWK4WbqEWK0VJn7xyhLUY0E7yWA46UozHqkkl7gaa4IBQ12IUSm5KD-WkyP717uWsIXHqZ1ABVsFjVTuVRcQXPzrdULOVqSDBA==
  title: ligonier.org
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFJViyrABvFmGH-R1zYSQSzl72a2cHagV39BePk-bjvHTqAsyP10MokSZKpIbqVXirMdwYA2PQPy5PFr2pYx8V8noqKad7VQtcLtR4i4jAEz2l3nyvky22BEn9NxRHF0yIeQgtljvry0-pawte2oXGkoREoVOA=
  title: eitan.bar
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQGbiVMH_Ei161benEKIKTFIVZdmtpgAS53-10r6h08P_W15GxGD_vfmIZ1zSLRHMvkdkp2yYuU3iELN397K2RQ7vbrzRC6Wkw44woFXyssOAoQ3QFWj9UZ9jbgpDxO1U0-Gqn_lj_QOcRmMibetKg==
  title: biblestudytools.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQH0GaYwWKez4FfnBM5wCUaxQgDnTDAAIa0ssg8omPZScGFXmS9C-W_IZoB-jd4VITzpdtr1CZLTfUlMa6d-w72bwGCH8JawaQ2dbawd_mEhrUekpzWkW1nnUt7-arEKA2YV-leYsEA1M5-DjOpdy_fKc2C179goiUwfrCoqiZEk1N6R54OyK6f5AIKXhyk=
  title: hebrew4christians.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQFhYc7ZxQ1mDSQBYkcvGgBdvl8dtX-RLFI7Iy_CdXeSuHRklK2Thzb4ZGIgFAsTIIM0ntxL-6tXR7fhBmuU8C0HbxyMBdPJZWlLiEdu5ezRwOJ4WX8Yjw7RnAJ-iqDw3F1-RE5M76OO0ncKE59zDfFpCTK-FOock8wAhDbH0eiTmu3XNNwujg==
  title: churchleaders.com
- uri: https://vertexaisearch.cloud.google.com/grounding-api-redirect/AUZIYQHlRJP5_QZPJhQ7bxDAFx4xIxG--ZmLscso85nV6fXLW9WyaOIyGKW4tJNbl82i65nEieLAps80HFubZ6iFaI9QzHAPQrZis7S3mpMdVeBl0eFI_HbsCCvj-KLALCuwJtaugzqriVh44IRThKurN3i3CEQL-NFiXWGSuyM-Y2w8D7XezmcJOY_9xA8W2avS8Ak=
  title: kcm.org
search_queries:
- ''
- hebrew word for covenant
- biblical definition of covenant
- greek word for covenant
- key bible verses about covenant OT and NT
- covenant bible trivia
revision: 1
revision_notes: 'Ability change request:

  Declare a suit. all other players give you a card of that suit. If they cannot,
  they reveal their hand.'
