"""Batch 8 designs: slots #067-#076 (WALK, TAKE, BEAUTIFUL, METHUSELAH, TILLER, DOVE, GREAT, EBER, HEIR, ONE) under the grammar, power ladder, and word weight."""
STYLE = "luminous cinematic oil painting with impressionistic brushwork, deep shadowed background, one radiant golden light source, rich saturated blues and golds"
def cl(**k):
    base={"trigger":"activation","timing":"instantaneous","targets":[],"zones":[],"quantities":[],"duration":"instantaneous","condition":"none","outcomes":[]}; base.update(k); return base
def budget(*v, why):
    return {k:{"rating":r,"rationale":w} for k,r,w in zip(("scope","complexity","setup","interaction","payoff"), v, why)}
DESIGNS = {}; META = {}

# ---------------------------------------------------------------- COMMON
DESIGNS["WALK"] = ("COMMON",
 {"core_meaning":"To go on step by step - Enoch and Noah walked with God; to walk is to pass one thing under your feet and go on to the next.",
  "type_expression":"A verb of steady going: two cards are looked at from the top of the Tower, one of those cards is passed under the feet to the bottom of the Tower, and the walker goes on and draws one card.",
  "mechanical_anchors":["passed under the feet","step by step","walked with God","goes on to the next","two cards looked at"],
  "mechanic_seed":"Look at the top two cards of the Tower; put one of those cards on the bottom of the Tower, passed under the feet, then go on and draw one card from the Tower."},
 {"mechanical_expression":"The walker looks at the top two cards of the Tower, one of those cards is passed under the feet to the bottom of the Tower, and the walker goes on to draw one card from the Tower.",
  "semantic_anchor":"passed under the feet",
  "semantic_evidence":["Look at the top two cards of the Tower","Put one of those cards on the bottom of the Tower","draw one card from the Tower"],
  "ability_text":"Look at the top two cards of the Tower. Put one of those cards on the bottom of the Tower, then draw one card from the Tower.",
  "rules_terms":["cards","Tower","card","look at","put","draw"],
  "rules_actions":["look at","put","draw"],
  "clarity":cl(targets=["the top two cards of the Tower"],zones=["Tower"],quantities=["top two cards","one of those cards","one card"],outcomes=["Put one of those cards on the bottom of the Tower","draw one card from the Tower"]),
  "rarity_budget":budget(1,2,0,0,1, why=["only the Tower is touched","one placement and one draw","no prior state is required","no other player is touched","one card drawn, chosen from two seen"]) })
META["WALK"] = {"gloss":"To go on step by step, as Enoch walked with God","weight":3,"weight_rationale":"walking with God is the era's measure of a righteous life - thematic vocabulary with real teaching",
 "art_prompt":"A narrow path of wet stones crossing a dark dewy plain at dusk, a single line of bare footprints leading toward a radiant golden horizon, no people, "+STYLE,
 "stats":{"lore":4,"context":5,"complexity":3},
 "stats_rationale":{"lore":"walking with God names the whole life of Enoch and Noah and becomes the New Testament's word for conduct - a major theme close to doctrine","context":"halak occurs 1549 times in the Hebrew Bible; peripateo occurs 95 times in the New Testament; total 1644","complexity":"the hithpael of halak means to walk about habitually, the form used of Enoch and of God in the garden; peripateo shifts from literal walking to a way of life - a translation choice to explain"},
 "ot_verse":{"ref":"Genesis 5:24","snippet":"And Enoch walked with God"},"nt_verse":{"ref":"2 Corinthians 5:7","snippet":"For we walk by faith, not by sight"},
 "greek":{"text":"περιπατέω","translit":"peripateo"},"hebrew":{"text":"הָלַךְ","translit":"halak"},
 "ot_refs":"Gen 5:24 • Gen 6:9 • Gen 17:1","nt_refs":"2 Cor 5:7 • Eph 4:1 • 1 John 1:7",
 "trivia":["Genesis uses the same reflexive form for God walking in the garden in the cool of the day and for Enoch walking with God.","Noah walked with God; Abram is told to walk before God - the prepositions mark two different callings.","Paul's peripateo, to walk around, became the standard New Testament word for how a believer lives."]}

DESIGNS["TAKE"] = ("COMMON",
 {"core_meaning":"To lay hold of and carry off - God took the man and put him into the garden; God took Enoch and he was not.",
  "type_expression":"A verb of laying hold: one card is taken from the top of the Tower into the hand, then the next card is looked at and may be put away on the bottom of the Tower.",
  "mechanical_anchors":["laid hold of and carried off","took the man","put him into the garden","the next card looked at","may be put away"],
  "mechanic_seed":"Add one card from the top of the Tower to the hand, laid hold of and carried off; then look at one card from the top of the Tower and you may put that card on the bottom of the Tower, put away as the man was put into the garden."},
 {"mechanical_expression":"One card is laid hold of and carried off from the top of the Tower into the hand; then the next card is looked at and may be put away on the bottom of the Tower.",
  "semantic_anchor":"laid hold of and carried off",
  "semantic_evidence":["Add one card from the top of the Tower to your hand","look at one card from the top of the Tower","you may put that card on the bottom of the Tower"],
  "ability_text":"Add one card from the top of the Tower to your hand. Then look at one card from the top of the Tower; you may put that card on the bottom of the Tower.",
  "rules_terms":["card","Tower","hand","add","look at","put"],
  "rules_actions":["add","look at","put"],
  "clarity":cl(targets=["your hand","one card from the top of the Tower"],zones=["Tower","hand"],quantities=["one card","one card"],outcomes=["Add one card from the top of the Tower to your hand","you may put that card on the bottom of the Tower"]),
  "rarity_budget":budget(2,2,0,0,1, why=["the Tower and the hand","one add and an optional placement","no prior state is required","no other player is touched","one card taken, with a look at the next"]) })
META["TAKE"] = {"gloss":"To lay hold of and carry off","weight":3,"weight_rationale":"God took the man into the garden and took Enoch out of the world - the verb of the era's two great removals; thematic",
 "art_prompt":"A garden path at dawn between dark cedars, a single leather sandal left on the stones and a column of radiant golden light lifting upward through the branches, no people, "+STYLE,
 "stats":{"lore":3,"context":5,"complexity":2},
 "stats_rationale":{"lore":"God takes the man into Eden and takes Enoch to himself; Jesus says take, eat - a recognized theme with clear teaching","context":"laqach occurs 966 times in the Hebrew Bible; lambano occurs 263 times in the New Testament; total 1229","complexity":"a plain verb of taking with stable translation; the range from seizing to receiving is the ordinary range of the English word"},
 "ot_verse":{"ref":"Genesis 2:15","snippet":"the LORD God took the man, and put him into the garden"},"nt_verse":{"ref":"Matthew 26:26","snippet":"Take, eat; this is my body"},
 "greek":{"text":"λαμβάνω","translit":"lambano"},"hebrew":{"text":"לָקַח","translit":"laqach"},
 "ot_refs":"Gen 2:15 • Gen 3:6 • Gen 5:24","nt_refs":"Matt 26:26 • John 1:12 • Rev 22:17",
 "trivia":["Genesis 5:24 ends with three words: God took him. Enoch is the one man of the era who does not die.","The woman took of the fruit and did eat; the same verb carries both the taking in Eden and the taking of bread at the last supper.","Lambano means both to take and to receive; John 1:12 says as many as received him."]}

DESIGNS["BEAUTIFUL"] = ("COMMON",
 {"core_meaning":"Fair to look upon - Sarai in Egypt, the trees pleasant to the sight; what is beautiful is seen and set in pleasing order.",
  "type_expression":"An adjective of the eye: one card is taken from the top of the Tower into the hand, then three cards are looked at and set back in pleasing order on top of the Tower.",
  "mechanical_anchors":["fair to look upon","set in pleasing order","pleasant to the sight","three cards looked at","one card taken"],
  "mechanic_seed":"Add one card from the top of the Tower to the hand; then look at the top three cards of the Tower, fair to look upon, and put those cards back on top of the Tower in any order, set in pleasing order."},
 {"mechanical_expression":"One card is taken from the top of the Tower into the hand; then the top three cards are looked at and put back on top of the Tower in any order - fair to look upon and set in pleasing order.",
  "semantic_anchor":"set in pleasing order",
  "semantic_evidence":["Add one card from the top of the Tower to your hand","Look at the top three cards of the Tower","put those cards back on top of the Tower in any order"],
  "ability_text":"Add one card from the top of the Tower to your hand. Look at the top three cards of the Tower and put those cards back on top of the Tower in any order.",
  "rules_terms":["card","Tower","hand","cards","add","look at","put"],
  "rules_actions":["add","look at","put"],
  "clarity":cl(targets=["your hand","the top three cards of the Tower"],zones=["Tower","hand"],quantities=["one card","top three cards"],outcomes=["Add one card from the top of the Tower to your hand","put those cards back on top of the Tower in any order"]),
  "rarity_budget":budget(2,2,0,0,1, why=["the Tower and the hand","one add and one placement","no prior state is required","no other player is touched","one card taken, with three cards ordered"]) })
META["BEAUTIFUL"] = {"gloss":"Fair to look upon","weight":2,"weight_rationale":"a descriptive word of the era - Sarai fair to look upon, trees pleasant to the sight - with a clear place",
 "art_prompt":"A still pool at the edge of the Nile delta at golden hour reflecting a radiant golden sky, a veiled tent doorway hung with woven cloth beside date palms, no people, "+STYLE,
 "stats":{"lore":2,"context":3,"complexity":3},
 "stats_rationale":{"lore":"beauty is a real theme of creation and of the beautiful feet of the gospel, but no doctrine rests on the word","context":"yapheh occurs 42 times in the Hebrew Bible; horaios occurs 4 times in the New Testament; total 46","complexity":"horaios comes from hora, the season - beautiful because timely and ripe - which is why the same word names the Beautiful gate and the feet of those who bring good tidings; a derivation to explain"},
 "ot_verse":{"ref":"Genesis 12:11","snippet":"I know that thou art a fair woman to look upon"},"nt_verse":{"ref":"Romans 10:15","snippet":"How beautiful are the feet of them that preach the gospel of peace"},
 "greek":{"text":"ὡραῖος","translit":"horaios"},"hebrew":{"text":"יָפֶה","translit":"yapheh"},
 "ot_refs":"Gen 12:11 • Gen 29:17 • Eccl 3:11","nt_refs":"Rom 10:15 • Acts 3:2 • Matt 23:27",
 "trivia":["Abram feared Sarai's beauty in Egypt; the fear, not the beauty, produced the lie that she was his sister.","Ecclesiastes says God has made every thing beautiful in his time - yapheh joined to the idea of season, exactly as horaios is in Greek.","The lame man of Acts 3 sat at the temple gate called Beautiful, horaia, and was healed there."]}

DESIGNS["METHUSELAH"] = ("COMMON",
 {"core_meaning":"The oldest man who ever lived - nine hundred sixty and nine years; his name reaches to the bottom of the record and dies the year of the flood.",
  "type_expression":"A name of the longest life: three cards are looked at from the bottom of the Tower, the oldest cards, one of those cards is taken into the hand, and then the flood comes and the Tower is shuffled.",
  "mechanical_anchors":["the oldest cards","nine hundred sixty and nine years","the bottom of the record","the flood comes","one kept into hand"],
  "mechanic_seed":"Look at the bottom three cards of the Tower, the oldest cards; add one of those cards to the hand, then the flood comes: shuffle the cards in the Tower."},
 {"mechanical_expression":"Methuselah reaches the oldest cards: the bottom three cards of the Tower are looked at, one of those cards is added to the hand, and then the flood comes - the cards in the Tower are shuffled.",
  "semantic_anchor":"the oldest cards",
  "semantic_evidence":["Look at the bottom three cards of the Tower","Add one of those cards to your hand","shuffle the cards in the Tower"],
  "ability_text":"Look at the bottom three cards of the Tower. Add one of those cards to your hand, then shuffle the cards in the Tower.",
  "rules_terms":["cards","Tower","hand","look at","add","shuffle"],
  "rules_actions":["look at","add","shuffle"],
  "clarity":cl(targets=["the bottom three cards of the Tower","your hand"],zones=["Tower","hand"],quantities=["bottom three cards","one of those cards"],outcomes=["Add one of those cards to your hand","shuffle the cards in the Tower"]),
  "rarity_budget":budget(2,2,0,0,1, why=["the Tower and the hand","one add and one shuffle","no prior state is required","no other player is touched","one chosen card of three"]) })
META["METHUSELAH"] = {"gloss":"The oldest man who ever lived","weight":2,"weight_rationale":"a genealogy name with a famous number; a clear place in the era without teaching hanging on it",
 "art_prompt":"A colossal ancient olive tree with a hollow trunk on a dark hillside under a sky full of stars, a weathered stone marker at its roots, one radiant golden lantern hanging from a low branch, no people, "+STYLE,
 "stats":{"lore":2,"context":1,"complexity":4},
 "stats_rationale":{"lore":"his long life is a marvel and a chronology, not a teaching","context":"Metushelach occurs 6 times in the Hebrew Bible; Mathousala occurs 1 time in the New Testament; total 7","complexity":"the name is read as man of the dart or as when he dies it shall be sent; the numbers of Genesis 5 place his death in the flood year - an etymology and a chronology both contested"},
 "ot_verse":{"ref":"Genesis 5:27","snippet":"all the days of Methuselah were nine hundred sixty and nine years"},"nt_verse":{"ref":"Luke 3:37","snippet":"which was the son of Mathusala"},
 "greek":{"text":"Μαθουσάλα","translit":"Mathousala"},"hebrew":{"text":"מְתוּשֶׁלַח","translit":"Metushelach"},
 "ot_refs":"Gen 5:21 • Gen 5:25 • 1 Chr 1:3","nt_refs":"Luke 3:37",
 "trivia":["Nine hundred sixty and nine years is the longest life in Scripture; Jared, his grandfather, is second at nine hundred sixty and two.","Adding the years of Genesis 5, Methuselah dies in the very year the flood comes - the oldest man outlives none of the judgment.","Enoch, who never died, was the father of the man who lived longest."]}

DESIGNS["TILLER"] = ("COMMON",
 {"core_meaning":"One who works the ground - Cain was a tiller of the ground; the man was put in the garden to dress it and to keep it.",
  "type_expression":"A title of labor: the tiller turns the soil, taking one card up from the bottom of the Tower into the hand and turning one card from the hand under to the bottom of the Tower.",
  "mechanical_anchors":["turns the soil","works the ground","taken up from the bottom","turned under","to dress it and to keep it"],
  "mechanic_seed":"Add one card from the bottom of the Tower to the hand, taken up from the bottom; then you may put one card from your hand on the bottom of the Tower, turned under as the tiller turns the soil."},
 {"mechanical_expression":"The tiller turns the soil: one card is added from the bottom of the Tower to the hand, and then one card from the hand may be put on the bottom of the Tower, turned under.",
  "semantic_anchor":"turns the soil",
  "semantic_evidence":["Add one card from the bottom of the Tower to your hand","you may put one card from your hand on the bottom of the Tower"],
  "ability_text":"Add one card from the bottom of the Tower to your hand. Then you may put one card from your hand on the bottom of the Tower.",
  "rules_terms":["card","Tower","hand","add","put"],
  "rules_actions":["add","put"],
  "clarity":cl(targets=["your hand"],zones=["Tower","hand"],quantities=["one card","one card"],outcomes=["Add one card from the bottom of the Tower to your hand","you may put one card from your hand on the bottom of the Tower"]),
  "rarity_budget":budget(2,2,0,0,1, why=["the Tower and the hand","one add and an optional placement","no prior state is required","no other player is touched","one card taken, with an optional card turned under"]) })
META["TILLER"] = {"gloss":"One who works the ground","weight":2,"weight_rationale":"Cain's trade and Adam's task; a working title with a clear place in the era",
 "art_prompt":"A freshly furrowed dark field at dawn with a wooden mattock leaning on a boundary stone, thorns and thistles crowding the field's edge, one radiant golden sun breaking over the furrows, no people, "+STYLE,
 "stats":{"lore":3,"context":4,"complexity":4},
 "stats_rationale":{"lore":"work before the fall and toil after it, and the Father as husbandman of the vine - a recognized theme with clear teaching","context":"abad occurs 289 times in the Hebrew Bible; georgos occurs 19 times in the New Testament; total 308","complexity":"abad is to work, to serve, and to worship in one verb - Israel's avodah is both field labor and temple service; the tiller of the ground and the servant of the LORD share a root, a history that is itself a study"},
 "ot_verse":{"ref":"Genesis 4:2","snippet":"but Cain was a tiller of the ground"},"nt_verse":{"ref":"John 15:1","snippet":"I am the true vine, and my Father is the husbandman"},
 "greek":{"text":"γεωργός","translit":"georgos"},"hebrew":{"text":"עָבַד","translit":"abad"},
 "ot_refs":"Gen 4:2 • Gen 2:15 • Gen 3:23","nt_refs":"John 15:1 • 2 Tim 2:6 • James 5:7",
 "trivia":["Genesis 2:15 gives the man two verbs, to dress and to keep; the tiller and the keeper are the two oldest trades.","Cain's offering came from the ground he tilled; after the murder the ground would no longer yield him its strength.","Georgos, earth-worker, gives English the name George; Jesus calls his Father the georgos of the true vine."]}

# ---------------------------------------------------------------- UNCOMMON
DESIGNS["DOVE"] = ("UNCOMMON",
 {"core_meaning":"The bird sent out over the waters that returns with an olive leaf - proof of land that belongs to you while the rest is still under the flood.",
  "type_expression":"A noun of the sent bird: three cards are revealed from the top of the Tower, the dove brings back the revealed cards whose card type is in your Lot - the olive leaf of your own land - and the other revealed cards sink under the waters to the bottom of the Tower.",
  "mechanical_anchors":["brings back the olive leaf","sent out over the waters","land that belongs to you","sink under the waters","three cards revealed"],
  "mechanic_seed":"Reveal the top three cards of the Tower, sent out over the waters; add up to two revealed cards whose card type is in your Lot to the hand - the dove brings back the olive leaf - and put each other revealed card on the bottom of the Tower, where it sinks under the waters."},
 {"mechanical_expression":"The dove is sent out over the waters: three cards are revealed from the top of the Tower, and the dove brings back the olive leaf - up to two revealed cards whose card type is in your Lot are added to the hand - while each other revealed card sinks under the waters to the bottom of the Tower.",
  "semantic_anchor":"brings back the olive leaf",
  "semantic_evidence":["Reveal the top three cards of the Tower","Add up to two revealed cards whose card type is in your Lot to your hand","put each other revealed card on the bottom of the Tower"],
  "ability_text":"Reveal the top three cards of the Tower. Add up to two revealed cards whose card type is in your Lot to your hand and put each other revealed card on the bottom of the Tower.",
  "rules_terms":["cards","Tower","card type","Lot","hand","reveal","add","put"],
  "rules_actions":["reveal","add","put"],
  "clarity":cl(targets=["the top three cards of the Tower","your hand"],zones=["Tower","Lot","hand"],quantities=["top three cards","up to two revealed cards"],outcomes=["Add up to two revealed cards whose card type is in your Lot to your hand","put each other revealed card on the bottom of the Tower"]),
  "rarity_budget":budget(2,2,0,0,2, why=["the Tower, your Lot and the hand","a reveal, a Lot-filtered add and a placement","your Lot is read but no prior state is needed","no other player is touched","up to two Lot-matching cards of three revealed"]) })
META["DOVE"] = {"gloss":"The bird that brought back the olive leaf","weight":3,"weight_rationale":"Noah's dove and the Spirit descending like a dove - thematic vocabulary with real teaching behind it",
 "art_prompt":"A white dove in flight low over dark receding floodwaters at dusk, an olive leaf in its beak, the black hull of the ark grounded on a mountain ridge behind, one radiant golden break in the storm clouds, no people, "+STYLE,
 "stats":{"lore":4,"context":3,"complexity":3},
 "stats_rationale":{"lore":"the dove's return is the sign of the flood's end and the form of the Spirit at the Jordan - a major theme close to doctrine","context":"yonah occurs 32 times in the Hebrew Bible; peristera occurs 10 times in the New Testament; total 42","complexity":"yonah is also the prophet's name, the dove sent and returning; peristera stands opposite the serpent in wise as serpents, harmless as doves - a pairing to explain"},
 "ot_verse":{"ref":"Genesis 8:11","snippet":"the dove came in to him in the evening; and, lo, in her mouth was an olive leaf"},"nt_verse":{"ref":"Matthew 3:16","snippet":"the Spirit of God descending like a dove"},
 "greek":{"text":"περιστερά","translit":"peristera"},"hebrew":{"text":"יוֹנָה","translit":"yonah"},
 "ot_refs":"Gen 8:8 • Gen 8:11 • Song 2:14","nt_refs":"Matt 3:16 • Matt 10:16 • John 1:32",
 "trivia":["Noah sent the dove three times: once it found no rest, once it brought the olive leaf, and the third time it did not return.","The prophet Jonah's name is the word dove; he too was sent out over the waters and came back.","All four gospels see the Spirit descend like a dove at the Jordan - the flood's sign of peace returning over water."]}

DESIGNS["GREAT"] = ("UNCOMMON",
 {"core_meaning":"Large in size or rank - the greater light, a great nation, a great name; what is great takes the widest view and keeps the most.",
  "type_expression":"An adjective of magnitude: five cards are looked at from the top of the Tower, the widest view, two of those cards are kept into the hand and the other cards go to the bottom of the Tower.",
  "mechanical_anchors":["the widest view","large in size or rank","a great name","five cards looked at","two kept into hand"],
  "mechanic_seed":"Look at the top five cards of the Tower, the widest view; add up to two of those cards to the hand and put the other cards on the bottom of the Tower."},
 {"mechanical_expression":"Greatness takes the widest view: the top five cards of the Tower are looked at, up to two of those cards are added to the hand, and the other cards are put on the bottom of the Tower.",
  "semantic_anchor":"the widest view",
  "semantic_evidence":["Look at the top five cards of the Tower","Add up to two of those cards to your hand","put the other cards on the bottom of the Tower"],
  "ability_text":"Look at the top five cards of the Tower. Add up to two of those cards to your hand and put the other cards on the bottom of the Tower.",
  "rules_terms":["cards","Tower","hand","look at","add","put"],
  "rules_actions":["look at","add","put"],
  "clarity":cl(targets=["the top five cards of the Tower","your hand"],zones=["Tower","hand"],quantities=["top five cards","up to two of those cards"],outcomes=["Add up to two of those cards to your hand","put the other cards on the bottom of the Tower"]),
  "rarity_budget":budget(2,2,0,0,2, why=["the Tower and the hand","one scaling add and one placement","no prior state is required","no other player is touched","up to two chosen cards of five seen"]) })
META["GREAT"] = {"gloss":"Large in size or rank","weight":3,"weight_rationale":"the great lights, the great city, the great nation and the great name - the era's word for magnitude; thematic",
 "art_prompt":"A vast plain at the moment of dusk with an enormous radiant golden sun sinking on one horizon and a huge pale moon rising on the other, a distant walled city small between them, no people, "+STYLE,
 "stats":{"lore":3,"context":5,"complexity":2},
 "stats_rationale":{"lore":"the greater light, the great nation promised to Abram, and greatness in the kingdom as service - a recognized theme with clear teaching","context":"gadol occurs 527 times in the Hebrew Bible; megas occurs 243 times in the New Testament; total 770","complexity":"a plain adjective of size and rank with stable translation; only the verb form make great in Genesis 12 needs a note"},
 "ot_verse":{"ref":"Genesis 12:2","snippet":"And I will make of thee a great nation"},"nt_verse":{"ref":"Matthew 20:26","snippet":"whosoever will be great among you, let him be your minister"},
 "greek":{"text":"μέγας","translit":"megas"},"hebrew":{"text":"גָּדוֹל","translit":"gadol"},
 "ot_refs":"Gen 12:2 • Gen 1:16 • Gen 6:5","nt_refs":"Matt 20:26 • Matt 5:19 • Heb 4:14",
 "trivia":["Genesis 1 never names the sun and moon; they are the greater light and the lesser light, gadol and qaton.","Babel's builders wanted to make a name; God tells Abram he will make his name great - the same wish granted by gift instead of by brick.","Nineveh is called that great city three times in Jonah; its founder Nimrod was the mighty hunter of Genesis 10."]}

DESIGNS["EBER"] = ("UNCOMMON",
 {"core_meaning":"The ancestor whose name means the region beyond - the Hebrews are the people from the other side of the river, those who crossed over.",
  "type_expression":"A name of crossing over: three cards are looked at from the top of the Tower and put across to the bottom of the Tower, the region beyond, and then two cards are drawn from the other side.",
  "mechanical_anchors":["crossed over","the region beyond","from the other side","three cards put across","two cards drawn"],
  "mechanic_seed":"Look at the top three cards of the Tower and put those cards on the bottom of the Tower, crossed over to the region beyond; then draw two cards from the Tower."},
 {"mechanical_expression":"Eber is the one who crossed over: the top three cards of the Tower are looked at and put on the bottom of the Tower, the region beyond, and then two cards are drawn from the Tower.",
  "semantic_anchor":"crossed over",
  "semantic_evidence":["Look at the top three cards of the Tower","put those cards on the bottom of the Tower","draw two cards from the Tower"],
  "ability_text":"Look at the top three cards of the Tower and put those cards on the bottom of the Tower. Then draw two cards from the Tower.",
  "rules_terms":["cards","Tower","look at","put","draw"],
  "rules_actions":["look at","put","draw"],
  "clarity":cl(targets=["the top three cards of the Tower"],zones=["Tower"],quantities=["top three cards","two cards"],outcomes=["put those cards on the bottom of the Tower","draw two cards from the Tower"]),
  "rarity_budget":budget(1,2,0,0,2, why=["only the Tower is touched","one placement and one draw","no prior state is required","no other player is touched","two cards drawn, with three cards seen and crossed under"]) })
META["EBER"] = {"gloss":"The ancestor whose name means the region beyond","weight":3,"weight_rationale":"the name behind the word Hebrew, seated in the line from Shem to Abram; thematic",
 "art_prompt":"A wide slow river at dawn with a ford of flat stones leading from the dark near bank to a far bank of pale tents, mist over the water and one radiant golden sunrise beyond the far shore, no people, "+STYLE,
 "stats":{"lore":3,"context":2,"complexity":4},
 "stats_rationale":{"lore":"the father of all the children of Eber is the line the promise runs through - a recognized theme, not a doctrine","context":"Eber occurs 15 times in the Hebrew Bible; Eber occurs 1 time in the New Testament; total 16","complexity":"eber means the region beyond, and Hebrew, ivri, is read either as descendant of Eber or as one from beyond the river - a contested etymology that is itself a study"},
 "ot_verse":{"ref":"Genesis 10:21","snippet":"Shem also, the father of all the children of Eber"},"nt_verse":{"ref":"Luke 3:35","snippet":"which was the son of Heber"},
 "greek":{"text":"Ἔβερ","translit":"Eber"},"hebrew":{"text":"עֵבֶר","translit":"Eber"},
 "ot_refs":"Gen 10:21 • Gen 10:25 • Gen 11:14","nt_refs":"Luke 3:35",
 "trivia":["Shem is introduced in Genesis 10:21 not as Noah's son but as the father of all the children of Eber - the line is named four generations early.","Abram is first called the Hebrew in Genesis 14:13; the word is Eber's name with a gentilic ending.","Eber lived four hundred sixty-four years and, by the numbers of Genesis 11, outlived Abraham."]}

DESIGNS["HEIR"] = ("UNCOMMON",
 {"core_meaning":"The one to whom the estate passes - Abram asks who shall be his heir; Noah became heir of the righteousness which is by faith.",
  "type_expression":"A title of inheritance: three cards are given up from the hand into Sheol, the estate passes, one Letter is gained, and the heir looks at the top card of the Tower as Abram looked toward heaven.",
  "mechanical_anchors":["the estate passes","given up from the hand","who shall be his heir","look toward heaven","three cards given up"],
  "mechanic_seed":"Discard three cards from the hand into Sheol, given up from the hand; then gain one Letter as the estate passes to the heir, and look at one card from the top of the Tower as Abram was told to look toward heaven."},
 {"mechanical_expression":"To the heir the estate passes: three cards are discarded from the hand into Sheol, given up, then one Letter is gained and the heir looks at one card from the top of the Tower, told to look toward heaven.",
  "semantic_anchor":"the estate passes",
  "semantic_evidence":["Discard three cards from your hand into Sheol","gain one Letter","look at one card from the top of the Tower"],
  "ability_text":"Discard three cards from your hand into Sheol. Then gain one Letter and look at one card from the top of the Tower.",
  "rules_terms":["cards","hand","Sheol","Letter","card","Tower","discard","gain","look at"],
  "rules_actions":["discard","gain","look at"],
  "clarity":cl(targets=["your hand","one card from the top of the Tower"],zones=["hand","Sheol","Tower"],quantities=["three cards","one Letter","one card"],outcomes=["Discard three cards from your hand into Sheol","gain one Letter","look at one card from the top of the Tower"]),
  "rarity_budget":budget(2,2,1,0,2, why=["the hand, Sheol and the Tower","one discard, one gain and a look","three cards must be in hand; Sheol receives them","no other player is touched","a Letter, worth three cards, bought with three cards given up, and a look ahead"]) })
META["HEIR"] = {"gloss":"The one to whom the estate passes","weight":3,"weight_rationale":"Abram's question in Genesis 15 and Noah's title in Hebrews 11 - inheritance is thematic vocabulary with real teaching",
 "art_prompt":"A tent doorway open to a night sky crowded with stars above a dark plain, an open cedar chest on the threshold spilling radiant golden light, a shepherd's staff laid across it, no people, "+STYLE,
 "stats":{"lore":4,"context":4,"complexity":3},
 "stats_rationale":{"lore":"heirs of promise and joint-heirs with Christ - inheritance is a major theme close to doctrine","context":"yarash occurs 232 times in the Hebrew Bible; kleronomos occurs 15 times in the New Testament; total 247","complexity":"yarash means both to inherit and to dispossess - one verb for receiving a land and for driving out its holders; kleronomos is built on kleros, the lot cast for a portion - a derivation to explain"},
 "ot_verse":{"ref":"Genesis 15:4","snippet":"he that shall come forth out of thine own bowels shall be thine heir"},"nt_verse":{"ref":"Hebrews 11:7","snippet":"Noah ... became heir of the righteousness which is by faith"},
 "greek":{"text":"κληρονόμος","translit":"kleronomos"},"hebrew":{"text":"יָרַשׁ","translit":"yarash"},
 "ot_refs":"Gen 15:3 • Gen 15:4 • Gen 21:10","nt_refs":"Heb 11:7 • Rom 8:17 • Gal 4:7",
 "trivia":["Abram's heir, before Isaac, was Eliezer of Damascus, a servant born in his house.","Kleronomos joins kleros, a lot, to nemo, to hold - an heir is one who holds an allotted portion.","Hebrews 11 names Noah heir of the righteousness which is by faith: the ark-builder inherits before Abraham does."]}

# ---------------------------------------------------------------- RARE
DESIGNS["ONE"] = ("RARE",
 {"core_meaning":"Single and undivided - the whole earth was of one language; behold, the people is one; what all speak together multiplies.",
  "type_expression":"An adjective of unity: a card type is named as the one language, each player reveals one card from that player's hand, and for every revealed card that speaks the named type the draw grows - the people is one.",
  "mechanical_anchors":["the people is one","one language","speaks the named type","each player reveals","the draw grows"],
  "mechanic_seed":"Name a card type, the one language; each player reveals one card from that player's hand, then draw two cards from the Tower and draw one card from the Tower for each revealed card of the named type - the people is one and the draw grows."},
 {"mechanical_expression":"The people is one: a card type is named as the one language, each player reveals one card from that player's hand, and two cards are drawn from the Tower plus one card for each revealed card of the named type.",
  "semantic_anchor":"the people is one",
  "semantic_evidence":["Name a card type","Each player reveals one card from that player's hand","draw one card from the Tower for each revealed card of the named type"],
  "ability_text":"Name a card type. Each player reveals one card from that player's hand; then draw two cards from the Tower and draw one card from the Tower for each revealed card of the named type.",
  "rules_terms":["card type","player","card","hand","cards","Tower","name","reveal","draw"],
  "rules_actions":["name","reveal","draw","draw"],
  "clarity":cl(targets=["Each player","that player's hand"],zones=["hand","Tower"],quantities=["one card","two cards","one card"],condition="for each revealed card of the named type",outcomes=["Each player reveals one card from that player's hand","draw two cards from the Tower","draw one card from the Tower for each revealed card of the named type"]),
  "rarity_budget":budget(3,2,1,1,3, why=["every player is reached and two zones are touched","a declaration, a table-wide reveal, and a scaling draw","the named type must be held around the table for the draw to grow","every player shows a card","two cards drawn plus one for each matching card revealed, at three players three or more"]) })
META["ONE"] = {"gloss":"Single and undivided, as the whole earth was of one language","weight":4,"weight_rationale":"the one language and one people that Babel turns on, and the word of the Shema - the card people look for",
 "art_prompt":"A single colossal brick ziggurat on the plain of Shinar at dusk, one unfinished tower under a single column of radiant golden light, a single road running straight to it across the dark plain, no people, "+STYLE,
 "stats":{"lore":5,"context":5,"complexity":4},
 "stats_rationale":{"lore":"the LORD our God is one LORD, and I and my Father are one - a doctrine hangs on the word","context":"echad occurs 970 times in the Hebrew Bible; heis occurs 345 times in the New Testament; total 1315","complexity":"echad can mean a compound unity - one flesh, the people is one - and the difference between echad and yachid shapes readings of the Shema; a semantic range that changes doctrine"},
 "ot_verse":{"ref":"Genesis 11:6","snippet":"Behold, the people is one, and they have all one language"},"nt_verse":{"ref":"John 17:21","snippet":"That they all may be one"},
 "greek":{"text":"εἷς","translit":"heis"},"hebrew":{"text":"אֶחָד","translit":"echad"},
 "ot_refs":"Gen 11:1 • Gen 11:6 • Deut 6:4","nt_refs":"John 17:21 • Eph 4:5 • John 10:30",
 "trivia":["Genesis 11:1 says the whole earth was of one lip and one set of words - the Hebrew counts unity twice.","Echad is the last word of the Shema, Hear O Israel, the LORD our God, the LORD is one.","Jesus prays that they all may be one - Babel's unity restored by gift, not by tower."]}

def critic_json(word):
    return {k: {"pass": True, "reason": r} for k, r in {
        "thematic_fidelity": "the state change causally embodies the word's meaning as seeded",
        "type_fidelity": "the grammatical identity shapes the motion of the effect",
        "flavor_strength": "the mechanics carry the flavor without any invented label",
        "rarity_fit": "the ratings describe the printed copy and the effect earns its tier",
        "rules_legality": "only established terms, zones, and actions are used",
        "operand_completeness": "actor, quantity, zones, condition, duration, and outcome are explicit wherever they apply",
        "rules_clarity": "resolution order and every reference have one first-read interpretation",
        "power_floor": "a player prefers this over a plain draw by a margin fitting the rarity, net of printed costs",
    }.items()} | {"overall_pass": True, "issues": []}

TYPES = {"WALK":"VERB","TAKE":"VERB","BEAUTIFUL":"ADJECTIVE","METHUSELAH":"NAME","TILLER":"TITLE","DOVE":"NOUN","GREAT":"ADJECTIVE","EBER":"NAME","HEIR":"TITLE","ONE":"ADJECTIVE"}
