"""Power-ladder redesigns (2026-08-28): DEEP, REDEEMER, DISCORD to RARE strength; KINGDOM to wild."""
def cl(**k):
    base={"trigger":"activation","timing":"instantaneous","targets":[],"zones":[],"quantities":[],"duration":"instantaneous","condition":"none","outcomes":[]}; base.update(k); return base
def budget(*v, why):
    return {k:{"rating":r,"rationale":w} for k,r,w in zip(("scope","complexity","setup","interaction","payoff"), v, why)}
DESIGNS = {
 "DEEP": ("RARE", "035-deep",
  {"core_meaning":"Reaching far beneath the surface - what lies at the bottom of the Tower is brought up, and what is not taken sinks to Sheol.",
   "type_expression":"An adjective of depth: the player looks at the bottom of the Tower, brings up to three cards up from beneath, lets the rest sink into Sheol, and draws once more from the top.",
   "mechanical_anchors":["from the bottom of the Tower","brought up from beneath","the rest sinks into Sheol","up to three from the deep","then one more from the top"],
   "mechanic_seed":"Look at the bottom four cards of the Tower; add up to three of those cards to the hand, put the other cards into Sheol so the rest sinks, then draw one card from the top."},
  {"mechanical_expression":"Depth is the bottom of the Tower: four cards are looked at from the bottom of the Tower, up to three are brought up from beneath into hand, the other cards sink into Sheol, and one more card is drawn from the top.",
   "semantic_anchor":"brought up from beneath",
   "semantic_evidence":["Look at the bottom four cards of the Tower","Add up to three of those cards to your hand","put the other cards into Sheol"],
   "ability_text":"Look at the bottom four cards of the Tower. Add up to three of those cards to your hand, put the other cards into Sheol, and then draw one card from the Tower.",
   "rules_terms":["cards","card","Tower","hand","Sheol","look at","add","put","draw"],
   "rules_actions":["look at","add","put","draw"],
   "clarity":cl(targets=["the bottom four cards of the Tower","your hand"],zones=["Tower","hand","Sheol"],quantities=["bottom four cards","up to three of those cards","one card"],outcomes=["Add up to three of those cards to your hand","put the other cards into Sheol","draw one card from the Tower"]),
   "rarity_budget":budget(2,3,1,0,3, why=["the Tower's bottom, the hand and Sheol","a look, a scaling add, a placement into Sheol, and a draw","the bottom of the Tower and Sheol are read","no other player is touched","up to three chosen cards plus one draw against one discard paid"])}),
 "REDEEMER": ("RARE", "047-redeemer",
  {"core_meaning":"The kinsman who buys back what was lost, paying the price himself.",
   "type_expression":"A title of office: the redeemer takes up to four lost cards back from Sheol, then pays the price - one card set on top of the Tower, one given into Sheol.",
   "mechanical_anchors":["buys back from Sheol","pays the price himself","up to four lost cards","one set on top","one given into Sheol"],
   "mechanic_seed":"Choose up to four cards in Sheol and add those chosen cards to the hand; then pay the price: put one card from the hand on top of the Tower and put one card from the hand into Sheol."},
  {"mechanical_expression":"The redeemer buys back from Sheol - up to four chosen cards return to hand - and pays the price himself: one card from hand goes on top of the Tower and one card from hand goes into Sheol.",
   "semantic_anchor":"buys back from Sheol",
   "semantic_evidence":["Choose up to four cards in Sheol and add those chosen cards to your hand","put one card from your hand on top of the Tower and put one card from your hand into Sheol"],
   "ability_text":"Choose up to four cards in Sheol and add those chosen cards to your hand. Then put one card from your hand on top of the Tower and put one card from your hand into Sheol.",
   "rules_terms":["cards","card","Sheol","hand","Tower","choose","add","put"],
   "rules_actions":["choose","add","put","put"],
   "clarity":cl(targets=["your hand"],zones=["Sheol","hand","Tower"],quantities=["up to four cards","one card","one card"],outcomes=["add those chosen cards to your hand","put one card from your hand on top of the Tower","put one card from your hand into Sheol"]),
   "rarity_budget":budget(2,3,1,0,3, why=["Sheol, the hand and the Tower","a scaling recovery and two placements","Sheol must hold cards worth taking","no other player is touched","up to four cards back for two cards paid, net two or more plus the one discard printed"])}),
 "DISCORD": ("RARE", "057-discord",
  {"core_meaning":"The sound of unity breaking into strife - every tongue is heard, one household is struck, and the sower of discord gathers.",
   "type_expression":"A noun of rupture: every player reveals a card, discord is sown against one chosen player whose two cards fall into Sheol, and the sower draws three.",
   "mechanical_anchors":["every tongue revealed","sown against one chosen player","two cards fall into Sheol","the sower draws three","confusion of tongues"],
   "mechanic_seed":"Each player reveals one card so every tongue is heard; then choose another player - that chosen player puts two cards from hand into Sheol - and the sower draws three cards from the Tower."},
  {"mechanical_expression":"Discord is heard first - each player reveals one card from that player's hand - then sown against one chosen player: two of that chosen player's cards fall into Sheol, and the sower draws three cards from the Tower.",
   "semantic_anchor":"sown against one chosen player",
   "semantic_evidence":["Each player reveals one card from that player's hand","that chosen player puts two cards from that chosen player's hand into Sheol","draw three cards from the Tower"],
   "ability_text":"Each player reveals one card from that player's hand. Then choose another player; that chosen player puts two cards from that chosen player's hand into Sheol, and draw three cards from the Tower.",
   "rules_terms":["player","card","cards","hand","Sheol","Tower","reveal","choose","put","draw"],
   "rules_actions":["reveal","choose","put","draw"],
   "clarity":cl(targets=["Each player","another player","That chosen player"],zones=["hand","Sheol","Tower"],quantities=["one card","two cards","three cards"],outcomes=["Each player reveals one card from that player's hand","that chosen player puts two cards from that chosen player's hand into Sheol","draw three cards from the Tower"]),
   "rarity_budget":budget(3,2,1,1,3, why=["every player reveals; one player and three zones are touched","a table-wide reveal, a forced two-card loss, and a three-card draw","the chosen player must hold cards; Sheol receives them","every player shows a card and one loses two","three cards drawn against one discard paid, with the opponent two cards poorer"])}),
 "KINGDOM": ("GLORIOUS", "039-kingdom",
  {"core_meaning":"The rule of a sovereign over every subject - a new order given to all, and the throne gathering what the realm has cast off.",
   "type_expression":"A noun of dominion: every player's Lot is returned and a new Lot revealed - the realm re-ordered - and the sovereign gathers up to four cards from Sheol.",
   "mechanical_anchors":["a new order given to all","every player's Lot returned","the realm re-ordered","the sovereign gathers from Sheol","up to four cards"],
   "mechanic_seed":"Each player returns that player's Lot to the Lots and reveals a new Lot from the Lots - a new order given to all - then the sovereign chooses up to four cards in Sheol and adds those chosen cards to the hand."},
  {"mechanical_expression":"Dominion re-orders the realm: each player returns that player's Lot and reveals a new Lot - every player's Lot returned - and then the sovereign gathers, choosing up to four cards in Sheol and adding those chosen cards to hand.",
   "semantic_anchor":"every player's Lot returned",
   "semantic_evidence":["Each player returns that player's Lot to the Lots and reveals a new Lot from the Lots","choose up to four cards in Sheol and add those chosen cards to your hand"],
   "ability_text":"Each player returns that player's Lot to the Lots and reveals a new Lot from the Lots. Then choose up to four cards in Sheol and add those chosen cards to your hand.",
   "rules_terms":["player","Lot","Lots","cards","Sheol","hand","return","reveal","choose","add"],
   "rules_actions":["return","reveal","choose","add"],
   "clarity":cl(targets=["Each player","that player's Lot","your hand"],zones=["Lot","Lots","Sheol","hand"],quantities=["a new Lot","up to four cards"],outcomes=["Each player returns that player's Lot to the Lots and reveals a new Lot from the Lots","add those chosen cards to your hand"]),
   "rarity_budget":budget(3,3,1,3,4, why=["every player's Lot and Sheol","a table-wide Lot renewal and a scaling recovery","Sheol must hold cards; every player holds a Lot","every player's Lot is replaced","four cards from Sheol plus a chapter re-ordered - against two discards paid"])}),
}
