"""MESSENGER, CHOOSE, ASCEND brought to UNCOMMON strength under the power ladder (2026-08-28)."""
def cl(**k):
    base={"trigger":"activation","timing":"instantaneous","targets":[],"zones":[],"quantities":[],"duration":"instantaneous","condition":"none","outcomes":[]}; base.update(k); return base
def budget(*v, why):
    return {k:{"rating":r,"rationale":w} for k,r,w in zip(("scope","complexity","setup","interaction","payoff"), v, why)}
DESIGNS = {
 "MESSENGER": ("UNCOMMON", "041-messenger",
  {"core_meaning":"One sent with word of a particular kind - the messenger names what is sought, reveals what the road holds, and brings back all of that kind.",
   "type_expression":"A title of office: the messenger names a card type, reveals the top three cards, brings up to two revealed cards of the named kind into hand, and leaves the rest on the road in chosen order.",
   "mechanical_anchors":["names the kind sought","reveals what the road holds","brings back the named kind","up to two of the named type","the rest left in order"],
   "mechanic_seed":"Name a card type and reveal the top three cards of the Tower; add up to two revealed cards of the named type to the hand, and put each other revealed card on top of the Tower in any order."},
  {"mechanical_expression":"The messenger names the kind sought - a card type - reveals the top three cards of the Tower, and brings back the named kind: up to two revealed cards of the named type go to hand, and the other revealed cards return to the top of the Tower in any order.",
   "semantic_anchor":"brings back the named kind",
   "semantic_evidence":["Name a card type and reveal the top three cards of the Tower","Add up to two revealed cards of the named type to your hand","put each other revealed card on top of the Tower in any order"],
   "ability_text":"Name a card type and reveal the top three cards of the Tower. Add up to two revealed cards of the named type to your hand and put each other revealed card on top of the Tower in any order.",
   "rules_terms":["card type","cards","Tower","hand","name","reveal","add","put"],
   "rules_actions":["name","reveal","add","put"],
   "clarity":cl(targets=["the top three cards of the Tower","your hand"],zones=["Tower","hand"],quantities=["top three cards","up to two revealed cards"],outcomes=["Add up to two revealed cards of the named type to your hand","put each other revealed card on top of the Tower in any order"]),
   "rarity_budget":budget(2,2,0,0,2, why=["the Tower and the hand","a declaration, a reveal, a scaling add, and a reorder","no prior state is required","no other player is touched","up to two cards of a named kind"])}),
 "CHOOSE": ("UNCOMMON", "043-choose",
  {"core_meaning":"To select and set apart - election that reaches into what was lost and picks out what the shared recipe needs.",
   "type_expression":"A verb of election: one card in Sheol whose card type the Chapter Lot needs is chosen and added to hand, and one more card is drawn from the Tower.",
   "mechanical_anchors":["elected out of Sheol","what the Chapter Lot needs","picked out and added","one more drawn","set apart"],
   "mechanic_seed":"Choose one card in Sheol whose card type is in the Chapter Lot - what the Chapter Lot needs - add that chosen card to the hand, then draw one card from the Tower."},
  {"mechanical_expression":"Election reaches into Sheol for what the Chapter Lot needs: one card whose card type is in the Chapter Lot is chosen and added to hand, and one more card is drawn from the Tower.",
   "semantic_anchor":"what the Chapter Lot needs",
   "semantic_evidence":["Choose one card in Sheol whose card type is in the Chapter Lot","add that chosen card to your hand","draw one card from the Tower"],
   "ability_text":"Choose one card in Sheol whose card type is in the Chapter Lot and add that chosen card to your hand. Then draw one card from the Tower.",
   "rules_terms":["card","Sheol","card type","Chapter Lot","hand","Tower","choose","add","draw"],
   "rules_actions":["choose","add","draw"],
   "clarity":cl(targets=["that chosen card","your hand"],zones=["Sheol","Chapter Lot","hand","Tower"],quantities=["one card","one card"],outcomes=["add that chosen card to your hand","draw one card from the Tower"]),
   "rarity_budget":budget(2,2,1,0,2, why=["Sheol, the Chapter Lot, the hand and the Tower","a filtered selection and a draw","Sheol must hold a card of a type the Chapter Lot names","no other player is touched","one chosen card and one draw"])}),
 "ASCEND": ("UNCOMMON", "056-ascend",
  {"core_meaning":"To climb upward toward heaven by human strength, and to take only what stands on the heights.",
   "type_expression":"A verb of climbing: the player scales the top four cards of the Tower, takes up to two cards of the heights - LORE three or more - and leaves the other rungs in chosen order.",
   "mechanical_anchors":["scales the top of the Tower","only the heights are taken","up to two of the heights","rungs left in order","LORE three or more"],
   "mechanic_seed":"Look at the top four cards of the Tower, take up to two of those cards that each have LORE three or more - the heights - into the hand, and put the other rungs on top of the Tower in any order."},
  {"mechanical_expression":"The climber scales the top four cards of the Tower; only the heights are taken - up to two cards that each have LORE three or more go to hand - and the other rungs are put back on top of the Tower in any order.",
   "semantic_anchor":"only the heights are taken",
   "semantic_evidence":["Look at the top four cards of the Tower","Add up to two of those cards that each have LORE three or more to your hand","put the other cards on top of the Tower in any order"],
   "ability_text":"Look at the top four cards of the Tower. Add up to two of those cards that each have LORE three or more to your hand and put the other cards on top of the Tower in any order.",
   "rules_terms":["cards","Tower","hand","LORE","look at","add","put"],
   "rules_actions":["look at","add","put"],
   "clarity":cl(targets=["the top four cards of the Tower","your hand"],zones=["Tower","hand"],quantities=["top four cards","up to two of those cards"],outcomes=["Add up to two of those cards that each have LORE three or more to your hand","put the other cards on top of the Tower in any order"]),
   "rarity_budget":budget(2,2,0,0,2, why=["the Tower and the hand","a four-card look, a stat-hooked scaling add, and a reorder","no prior state is required","no other player is touched","up to two high-LORE cards of four"])}),
}
